# -*- coding: utf-8 -*-
"""stream.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lj6CW_XcJQeaRcIt5bDbcOqh6xbT1PNf

conda activate myenv
cd C:\Users\HP\OneDrive\Dokumente\DataScientest
streamlit run stream.py
"""

import streamlit as st

# Seitenleiste

st.sidebar.markdown('<style>div.row-widget.stRadio div{color: white;}</style>', unsafe_allow_html=True)
# st.sidebar.write('<font color="white">Main Menu</font>', unsafe_allow_html=True)
page = st.sidebar.radio(" ", ["Home", "Introduction",
                              "Exploration Analysis - NASA",
                              "Exploration Analysis - OWID",
                              "Exploration Analysis - FAO",
                            "Modeling preparation",
                            "Model 1",
                            "Model 2",
                            "Time-series modeling with SARIMA",
                            "Conclusion", "Credits"])